OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes
#WPM_ENABLE = yes
VIA_ENABLE = no
MOUSEKEY_ENABLE = yes

# conflicts with spacecadet
COMMAND_ENABLE = no
